### ISSUE TITLE
A question about multiview 

### ISSUE THREAD

**Issue by lisa676** [zju3dv/EasyMocap#12]
I'm thankful for your this great work. I check your work output and it gives output of related camera. I mean if input is 3 cameras then it can output of related camera (input of camera 1 --> output of camera 1, input of camera 2 --> output of camera 2, input of camera 3 --> output of camera 3) or we can get even single output by selected camera.

Here my question is that there is no fusion in multiview inputs to get a fused output of all input cameras as in [MVPose](https://github.com/zju3dv/mvpose), [cross_view_pose video](https://www.youtube.com/watch?v=CbTUC7kOk9o) etc. So is there anyway to get output like these projects?

**Comment by chingswy** [comment]
We do not implement this because we do not know how to define the `fusion view` in all cases. It's too troublesome to set the camera parameters when rendering. In mvpose, we used matplotlib to visualize the mesh where we set the viewpoint manually.
You can also visualize the results by other render methods, such as Open3D, Blender. We will implement the Open3D version later.
