### ISSUE TITLE
Camera extrinsic parameters

### ISSUE THREAD

**Issue by Xianjin111** [zju3dv/EasyMocap#2]
Thank you for your perfect work. I have a question about the extri.yml of the provided example multiview dataset.  In the provided extri.yml, what's the difference between the R_1 and Rot_1? If I prepared my own datasets, should I put the rotation vector of camera in Rot_1? What's more, how to obtain the R_1?

Another question is if I obtained the smpl parameter in json, how can I obtain the mesh?

Thank you very much.

**Comment by chingswy** [comment]
`R_1` means a rotation vector(3x1) while `Rot_1` means the rotation matrix(3x3).
You can check the code of [this function.](https://github.com/zju3dv/EasyMocap/blob/master/code/mytools/camera_utils.py#L130) to prepare your own datasets. The rotation vector can be calculated from rotation matrix with `cv2.Rodrigues`.

The vertices of the mesh can be obtained as [this](https://github.com/zju3dv/EasyMocap/blob/master/code/demo_mv1pmf_smpl.py#L127). `body_model.faces` is the name of the faces.

**Comment by Xianjin111** [comment]
> `R_1` means a rotation vector(3x1) while `Rot_1` means the rotation matrix(3x3).
> You can check the code of [this function.](https://github.com/zju3dv/EasyMocap/blob/master/code/mytools/camera_utils.py#L130) to prepare your own datasets. The rotation vector can be calculated from rotation matrix with `cv2.Rodrigues`.
> 
> The vertices of the mesh can be obtained as [this](https://github.com/zju3dv/EasyMocap/blob/master/code/demo_mv1pmf_smpl.py#L127). `body_model.faces` is the name of the faces.

Got it! Thank you so much.

**Comment by carlosedubarreto** [comment]
I tryied to understand how to use this function  https://github.com/zju3dv/EasyMocap/blob/master/code/mytools/camera_utils.py#L130 
 to calibrate de camera, but I couldnt understand.
Can you maybe give me some simple hints?

I'm trying to understand how to calibrate using some tutorial on opencv, but I'm afraid those tutorial wont help because of the multiple camera setup that is used.

**Comment by chingswy** [comment]
You can calibrate your multiple cameras system step by step:
0. Prepare your chessboard
1. **Distortion** and **Intrinsic Parameter** Calibration for each camera individually.
2. **Extrinsic Parameter** Calibration
    You can simply do this by capturing your chessboard from all the cameras at the same time. And just use the `cv2.solvePnP` function  to calibrate the extrinsic parameters.
3. (Optional) Bundle Adjustment

**Comment by carlosedubarreto** [comment]
Thanks a lot, i'll study it.

**Comment by carlosedubarreto** [comment]
Hi @chingswy ,
I've been studying this for the last 2 days, and now things are making more sense, but I still have some doubts.

Please, can you confirm if I'm following the right direction?

The the steps 0 and 1 where clear to me, but the step 2 was bugging since I saw your answer.

On step 2 you said to capture the chessboard from all the cameras at the same time. What I understood is that this is needed so all the cameras can solve for each camera own coordinate system in all cameras at the same time, and that is how easymocap can understand the relation between all the cameras..


Is this step by step correct? (I'm just trying to be more specific based on what you answered me)
0 - Prepare a calibration chessboard
1 - Distortion and Intrinsic Paremeter: Calibrate each camera individually (something we can easily find tutorials about)
2 - Extrinsic Parameter: record several frames using all the cameras at the same time, and use these frames to calculate the "cv2.calibrateCamera" and then "cv2.solvePnP"

With these steps, save the respective "intri.yml" and "extri.yml" and that camera setup can be used with EasyMocap, right?

If what I wrote is correct, I would just need some more hints on how I'll have to deal with the calibration...
For example, I have the recording on all the cameras at the same time, so I'll have one video for each camera. These videos I can process them individually?

This is another thing that I'm having problems to understand, if the multi camera recording, if I have to processes all the videos togheter (im some way that I have no idea how to do yet) or if I can process the multi camera recording video of each camera on its own (I have an idea of how to do that), for example. Process the "cv2.calibrateCamera" and then "cv2.solvePnP" for camera 1, then for camera 2 and etc... 

Thanks a lot for the attention and answers. And sorry for this long text. I'm trying my best to get how to use easymocap, even if it took me weeks... It seems the best result I saw comparing to other solutions I've tested.

**Comment by chingswy** [comment]
@carlosedubarreto An example of a simple extrinsic calibration can be found in `./scripts/calibration`. Hope it helps you.

**Comment by carlosedubarreto** [comment]
Thanks a lot!!!!!!!!!!!

**Comment by ahsan3803** [comment]
@carlosedubarreto  I was using [this camera calibration tool](https://github.com/prclibo/calibration-toolbox). You can have a look as it is good one. I didn't use for EasyMocap but I used it for MVPose.

**Comment by carlosedubarreto** [comment]
@ahsan3803 Thanks for the tip, but its for Matlab. 
But now I think I'm getting better on calibrating my cameras. :)
