### ISSUE TITLE
blender showing error while importing mocap

### ISSUE THREAD

**Issue by Dev5896** [zju3dv/EasyMocap#37]
![3](https://user-images.githubusercontent.com/85992730/122650876-e84fcf00-d152-11eb-9f44-583edf208766.png)
help me how to solve this i have installed the updated easy mocap and mocap import addon

**Comment by carlosedubarreto** [comment]
To import in blender using the mocap_import addon, you should use the SMPLX model
This problem is more related to mocap import and not easymocap.

There is this issue talking about a similar problem in
https://github.com/carlosedubarreto/b3d_mocap_import/issues/15#issuecomment-864196673

We should continue the discussion there, if this issue I posted doesnt help you with the problem.

So we dont disturb this issue that is not related with easymocap 😉
We continue there, ok?

**Comment by Dev5896** [comment]
yeah ok 😄
