### ISSUE TITLE
Strange output of bvh

### ISSUE THREAD

**Issue by Sheltim233** [zju3dv/EasyMocap#427]
Hi, I am working with this amazing project, but when i was doing mono-video, I tried to export the bvh file through convert2bvh.py. In blender my output is weird because the left leg is always up, to be more specific, the L_hip. I got stuck by this for a week, can someone enlighten me about that? The output begins wired since 'Mypare', before which the output seems all good. Is it something wrong with convert2bvh.py or is it something wrong with 'Mypare'? Thanks a lot for your possible assistance!!!!!![image](https://github.com/user-attachments/assets/f1d6381a-8628-40af-8a0a-fa16e04c1208) @chingswy @yzhang-gh @rdenubila @peabody124 @carlosedubarreto

**Comment by carlosedubarreto** [comment]
Hello @Sheltim233 ,
Sorry I'm far from this things involving SMPL, since I had a problem with the company that sells the license to the model, and I cant even suggest a link to you, since I also had to unpublish all the code I've done for easymocap, easymocap monocular and others.
Also had to shut down my patreon becuase there was a lot of code related to SMPL model over there.


I plan to put all my codes on github, but it will take a long time for me to do that.
So, sorry I wont be able to help much now.

**Comment by Sheltim233** [comment]
@carlosedubarreto It's OK, thanks for reply

**Comment by raflitp** [comment]
Does the keypoints3d looks the same or it looks normal ? And what steps did you do which code you ran ?

**Comment by Sheltim233** [comment]
@raflitp Thanks for reply, I've fixed it by inspecting the output 'poses',  I am closing this issus.
