### ISSUE TITLE
[Quick Start] Lack of annots in the example dataset.

### ISSUE THREAD

**Issue by ShenhanQian** [zju3dv/EasyMocap#46]
First, I would like to thank you for your efforts in this amazing repo! I was trying to go through [Quick Start](https://github.com/zju3dv/EasyMocap/blob/master/doc/quickstart.md) and found a  gap between the example dataset and the code.

First, I ran `scripts\preprocess\extract_video.py` to extract frames from the given videos with `--no2d` as the `openpose` results are already included in the data pack.
Then, I ran `mv1p.py` to fit SMPL-X parameters as instructed, but the program just cannot correctly load the annotations. The `MV1PMF` dataset class loads JSON with `read_annot` in `easymocap\mytools\file_utils.py`, which is different from the default key formats in `openpose`'s results. It looks like that there should be a script to transform JSON files from `openpose` before fed into `read_annot`.

Did I miss anything? Thanks in advance.

**Comment by carlosedubarreto** [comment]
Hello,
I think the issue is that you are running with the `--no2d` flag
try to run without it. Like its on here:
https://github.com/zju3dv/EasyMocap/blob/master/doc/quickstart.md#demo

you could run this
`python3 scripts/preprocess/extract_video.py ${data} --handface`

then this 
`python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl`



For example, in windows, I run this:
`python scripts/preprocess/extract_video.py 0_input/sample`

and then:
python apps/demo/mv1p.py 0_input/sample --out 1_output/sample --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl

in this example, I have unpacked the sample files inside the folder '0_input' , inside easymocap folder

**Comment by chingswy** [comment]
Thanks @carlosedubarreto !
In the example dataset, I show how to convert the output of openpose to our annots, so you should remove the `--no2d` flag to automatic convert the output of openpose to our format.

**Comment by ShenhanQian** [comment]
Yeah, the problem is caused by `--no2d`, and removing it solved my problem. Thanks a lot! @carlosedubarreto @chingswy
